# Generated by Django 6.0.3 on 2026-04-02 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('ingredients', models.TextField(default='[]')),
                ('steps', models.TextField(default='[]')),
                ('cooking_time', models.CharField(max_length=100)),
                ('tools_used', models.TextField(default='[]')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('ai_note', models.TextField(blank=True)),
                ('result_type', models.CharField(choices=[('extracted_recipe', 'Extracted Recipe'), ('estimated_recipe', 'Estimated Recipe')], default='estimated_recipe', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_result', to='videos.videorequest')),
            ],
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='recipes.reciperesult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'recipe_result')},
            },
        ),
    ]
