# Generated by Django 4.2.29 on 2026-04-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperesult',
            name='country_of_origin',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='reciperesult',
            name='detected_language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
    ]
